// Generated by scripts/generate-ui-icons.mjs from Lucide.
// Do not edit icon geometry by hand. See THIRD_PARTY_NOTICES.md for licensing.

const SVG_NAMESPACE = 'http://www.w3.org/2000/svg';

const ICONS = Object.freeze({
  "search": [
    [
      "path",
      {
        "d": "m21 21-4.34-4.34"
      }
    ],
    [
      "circle",
      {
        "cx": "11",
        "cy": "11",
        "r": "8"
      }
    ]
  ],
  "close": [
    [
      "path",
      {
        "d": "M18 6 6 18"
      }
    ],
    [
      "path",
      {
        "d": "m6 6 12 12"
      }
    ]
  ],
  "bookmark": [
    [
      "path",
      {
        "d": "M17 3a2 2 0 0 1 2 2v15a1 1 0 0 1-1.496.868l-4.512-2.578a2 2 0 0 0-1.984 0l-4.512 2.578A1 1 0 0 1 5 20V5a2 2 0 0 1 2-2z"
      }
    ]
  ],
  "chevron": [
    [
      "path",
      {
        "d": "m6 9 6 6 6-6"
      }
    ]
  ],
  "open": [
    [
      "path",
      {
        "d": "M15 3h6v6"
      }
    ],
    [
      "path",
      {
        "d": "M10 14 21 3"
      }
    ],
    [
      "path",
      {
        "d": "M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"
      }
    ]
  ],
  "merge": [
    [
      "path",
      {
        "d": "M14 3a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1"
      }
    ],
    [
      "path",
      {
        "d": "M19 3a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1"
      }
    ],
    [
      "path",
      {
        "d": "m7 15 3 3"
      }
    ],
    [
      "path",
      {
        "d": "m7 21 3-3H5a2 2 0 0 1-2-2v-2"
      }
    ],
    [
      "rect",
      {
        "x": "14",
        "y": "14",
        "width": "7",
        "height": "7",
        "rx": "1"
      }
    ],
    [
      "rect",
      {
        "x": "3",
        "y": "3",
        "width": "7",
        "height": "7",
        "rx": "1"
      }
    ]
  ],
  "stack": [
    [
      "path",
      {
        "d": "M12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83z"
      }
    ],
    [
      "path",
      {
        "d": "M2 12a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 12"
      }
    ],
    [
      "path",
      {
        "d": "M2 17a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 17"
      }
    ]
  ],
  "trend": [
    [
      "path",
      {
        "d": "M16 7h6v6"
      }
    ],
    [
      "path",
      {
        "d": "m22 7-8.5 8.5-5-5L2 17"
      }
    ]
  ],
  "copy": [
    [
      "rect",
      {
        "width": "14",
        "height": "14",
        "x": "8",
        "y": "8",
        "rx": "2",
        "ry": "2"
      }
    ],
    [
      "path",
      {
        "d": "M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"
      }
    ]
  ],
  "dedupe": [
    [
      "line",
      {
        "x1": "12",
        "x2": "18",
        "y1": "15",
        "y2": "15"
      }
    ],
    [
      "rect",
      {
        "width": "14",
        "height": "14",
        "x": "8",
        "y": "8",
        "rx": "2",
        "ry": "2"
      }
    ],
    [
      "path",
      {
        "d": "M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"
      }
    ]
  ],
  "trash": [
    [
      "path",
      {
        "d": "M10 11v6"
      }
    ],
    [
      "path",
      {
        "d": "M14 11v6"
      }
    ],
    [
      "path",
      {
        "d": "M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6"
      }
    ],
    [
      "path",
      {
        "d": "M3 6h18"
      }
    ],
    [
      "path",
      {
        "d": "M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"
      }
    ]
  ]
});

export function createIcon(name) {
  const resolvedName = Object.hasOwn(ICONS, name) ? name : 'close';
  const svg = document.createElementNS(SVG_NAMESPACE, 'svg');
  svg.setAttribute('viewBox', '0 0 24 24');
  svg.setAttribute('aria-hidden', 'true');
  svg.setAttribute('focusable', 'false');
  svg.setAttribute('fill', 'none');
  svg.setAttribute('stroke', 'currentColor');
  svg.setAttribute('stroke-width', '2');
  svg.setAttribute('stroke-linecap', 'round');
  svg.setAttribute('stroke-linejoin', 'round');
  svg.classList.add('action-icon', 'lucide', `lucide-${resolvedName}`);

  for (const [tagName, attributes] of ICONS[resolvedName]) {
    const node = document.createElementNS(SVG_NAMESPACE, tagName);
    for (const [attribute, value] of Object.entries(attributes)) {
      node.setAttribute(attribute, String(value));
    }
    svg.append(node);
  }

  return svg;
}
